stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./gradlew build
  tags:
    - linux
    - java

deploy:
  stage: deploy
  script:
    - ./gradlew publish
  tags:
    - linux
    - java
  only:
    - tags